# Generated by Django 2.2.7 on 2019-11-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
