# Generated by Django 2.2.7 on 2019-11-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
    ]
